version: "3.7"

services:
  web:
    build: .
    image: rodrigoff/device-flow-proxy
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"